version: '3.6'

services:
  app:
    image: python:3.6.8
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "7999:7999"
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    stdin_open: true
    tty: true